### PR TITLE
TWEAK: allow quantile to be disabled

### PR DESCRIPTION
**Pull request by taylorchu**

### CODE REVIEW

**Comment by johnkeates** [comment]
Hi @taylorchu what does this do, and for which protocol/sink?

**Comment by taylorchu** [comment]
@johnkeates sorry for the late response.

We use librato, and it is charged per key. We need a way to disable quantile completely to reduce the cost by 40%.

**Comment by johnkeates** [comment]
Alright, seems like a reasonable need. However, I do wonder if this is something you could fix in the liberato sink instead? Right now, it would be something that happens statsite-wide, yet it is a liberato specific need. Another option would be a setting or something like that. The problem is that people might already be depending on the check and changing the way it works now  might break their setups.

**Comment by taylorchu** [comment]
1. I think this could be a system-wide feature because the cost is usually proportional to the number of keys. The cost could be disk storage to store, bandwidth to transfer, or cpu to compute quantile-key, etc; it just happens that in this case, we actually pay more money. It could benefit other sinks too.

2. This is almost backward-compatible because empty quantile was an invalid config before, and it still has the same default value now. The users will need to explicitly use `quantiles=` to disable quantile. It is really unlikely that they use `quantiles=` and expect quantiles to work.

**Comment by johnkeates** [comment]
That makes sense, I think we could merge it. I do wonder if this is tested as well, as in, with the unit tests and integration tests. Checks seem to have passed, so I suppose it means that we're good. I'll merge it and if things start setting themselves on fire we'll know where to look ;-)

**Pull request merged**
