### PR TITLE
Graphite sink whitespaces

### PR DESCRIPTION
**Pull request by yvlasenko**
- removed prefix special handling as it is always defined (might need bool handling but it should be done on class init)
- ensure no spaces and slashes in metric name, replace with underscore

### CODE REVIEW

**Comment by johnkeates** [comment]
Does graphite never allow for spaces? Or is that implementation specific.

**Comment by yvlasenko** [comment]
spaces might be supported but not with plaintext protocol as it expects space-separated data:
`<metric path> <metric value> <metric timestamp>`

**Comment by johnkeates** [comment]
Thank you got the PR, took me a bit to get around to checking the protocol spec but here ya go.

**Comment by drawks** [comment]
FWIW Spaces are supported when sending to carbon using pickle serialized data and have historically been supported in the graphite-web front end as well.

**Pull request merged**
