### PR TITLE
reduce stack size of handler thread to 256KB instead default 8MB

### PR DESCRIPTION
**Pull request by tantra35**
I think that 256KB is enough to so simple thread

### CODE REVIEW

**Comment by johnkeates** [comment]
Hi @tantra35 , the CI check is currently not passing. Please check out the logs, and update your PR, if it clears I'll have a look at your commit. Thanks!

**Comment by drawks** [comment]
Can someone kick off a fresh travis.ci run here, the existing run references the project before it was moved under the statsite organization and thusly doesn't point to any test results at the moment.

**Comment by johnkeates** [comment]
On it

**Comment by johnkeates** [comment]
Travis was too broken, since we're still cleaning up and picking up slack, merging and checking the build afterwards instead.

**Comment by drawks** [comment]
Woh?! really is it a good plan to merge the change to master without ever getting a clean build/test cycle?

**Comment by johnkeates** [comment]
No, I did the test afterwards, the problem was that the PR had a static reference to the old Travis instance. By merging some other PR's on top of yours we basically 'included' your PR in the 'next' PR.

**Comment by drawks** [comment]
ah I see

**Pull request merged**
