### PR TITLE
Build improvements, Debian packaging, update check for slightly better build platform support

### PR DESCRIPTION
**Pull request by johnkeates**
A few changes and cleanups made:

- Debian packaging support
- A manpage
- Using autoreconf to do updates for the make process instead of bootstrapping manually
- boilerplate autoreconf is now in autogen.sh as directed by the autotools guys
- Added install.md for some more details, useful for people running this on less-general platforms
- Added an initial configuration file for a CentOS vagrant box if someone were to need it for RPM testing or building in a clean environment
- check tests are now called and built using autotools
- integration tests with pytest bumped to a slightly higher version to fix a few bugs on newer systems
- added a -v flag to statsite to print the compiled version (#179)
- added buildconfig.h to pipe the version set in configure.ac to the actual C code
- removed a few temporal files that might not work on all platforms and should be regenerated on whatever system you want to build it on (#212)
- updated travis config

There are a bunch of tiny cleanups, typos etc. that were taken care of too. To make sure my PR's don't break Travis again, I'll check them first before submitting ;-)

### CODE REVIEW

**Comment by johnkeates** [comment]
Ping

**Comment by armon** [comment]
@johnkeates Sorry about the delay, work has been hectic. It's hard to review this PR, it's just so large. Can you please split it into smaller logical pieces? For example the version flag which is code change, vs packaging changes, etc. Not sure if there are auto generated files in the PR as well, since 28K LOC seems like a large addition. Can those be removed and just auto generated as needed?

**Comment by johnkeates** [comment]
No problem, let me explain what changes are here:

- A few edits in Makefile.am and configure.ac to accommodate the version number
- About 5 lines to add the -v option to the statsite binary
- An install.md doc to have platform-specific instructions as there seem to be people targeting non RPM/DEB platforms
- The /debian dir
- Modification to travis-ci to match the 'manual' build process

The big mass change was an upgrade to check-0.10 due to their changes in their build system being at that version. This is because it apparently otherwise doesn't play well with newer autotools versions and doesn't work on special linux distros.

**Comment by armon** [comment]
@johnkeates It looks like there are files from check 0.10 that might be auto generated in the PR however, could you strip those before merge? Thanks!

**Comment by johnkeates** [comment]
@armon I'll check it out, I basically just plugged the new version in and didn't change anything, because I just wanted it to work.

**Comment by johnkeates** [comment]
I couldn't figure out what the exact changes (and build-time generated files) were, so I just dumped it all and copied a fresh check-0.10.0 download in. I noticed it does come with a "configure" and a "Makefile.in" by default, but that should be fine since it was designed to be released that way. I could in theory remove those as well, and have autoreconf regenerate them every time, but since we're not going to change check ourselves (at least I'm not gonna mess with that), it shouldn't really matter. The automatic building does still work after removing the few files, so that's good.

**Comment by johnkeates** [comment]
I'm going to merge my own PR here. It's not a good procedure, but we'll have to get started somewhere.

**Pull request merged**
